# A blog about coding, life and everything in between
title: "925coder - An everyday programmer's blog"
email: 925coder@gmail.com
description: "Adventures in programming, life and everything else"
baseurl: "/betablog/"
url: "http://localhost:4000"

# Build settings
markdown: rdiscount
kramdown:
  input: GFM